// ============== بنك أسئلة القدرات ==============

export const VERBAL_QUESTIONS = [
  { id: 1, section: 'lafzy', subsection: 'vocabulary', q: 'الحَصافة في الرأي صفةُ العقلاءِ. معنى الحصافة:', options: ['السرعة', 'الإحكام والإتقان', 'التردد', 'الغموض'], correct: 1 },
  { id: 2, section: 'lafzy', subsection: 'vocabulary', q: 'نَكَبَ المسافرُ عن الطريق. معنى نكب:', options: ['سار فيه', 'عاد إليه', 'مال وعَدَلَ عنه', 'تتبّعه'], correct: 2 },
  { id: 3, section: 'lafzy', subsection: 'vocabulary', q: 'الرجلُ مِفضالٌ على قومه. معنى مِفضال:', options: ['كثير الفضل والعطاء', 'متكبر', 'متواضع جدًا', 'بخيل'], correct: 0 },
  { id: 4, section: 'lafzy', subsection: 'vocabulary', q: 'أَلَمَّ الحزنُ بقلبه. معنى ألمّ:', options: ['ابتعد عنه', 'نزل به وأصابه', 'خفّ عنه', 'تجاوزه'], correct: 1 },
  { id: 5, section: 'lafzy', subsection: 'vocabulary', q: 'كلامُه يَنِمُّ عن ثقافةٍ واسعةٍ. معنى ينم:', options: ['يُخفي', 'يُظهر ويكشف', 'يُضعف', 'يُنكر'], correct: 1 },
  { id: 6, section: 'lafzy', subsection: 'vocabulary', q: 'رجلٌ أَرِيبٌ في تصرفاته. معنى أريب:', options: ['جاهل', 'متهور', 'ذكي حاذق', 'متردد'], correct: 2 },
  { id: 7, section: 'lafzy', subsection: 'vocabulary', q: 'ذاع صِيتُه بين الناس. معنى صيت:', options: ['انتشر ذكره وشهرته', 'اختفى أمره', 'قلّت معرفته', 'تغيّر حاله'], correct: 0 },
  { id: 8, section: 'lafzy', subsection: 'vocabulary', q: 'الجوادُ مَطِيَّةُ الكريم. معنى مطية:', options: ['عداوته', 'ما يُركَب عليه', 'صديقه', 'خصمه'], correct: 1 },

  { id: 9, section: 'lafzy', subsection: 'analogy', q: 'كتاب : فصل', options: ['قلم : حبر', 'بيت : غرفة', 'شجرة : ورقة', 'جيش : قائد'], correct: 1 },
  { id: 10, section: 'lafzy', subsection: 'analogy', q: 'طبيب : مستشفى', options: ['تلميذ : دفتر', 'مهندس : مكتب', 'معلم : مدرسة', 'طيار : سماء'], correct: 2 },
  { id: 11, section: 'lafzy', subsection: 'analogy', q: 'جوع : طعام', options: ['نوم : فراش', 'تعب : راحة', 'ضحك : فرح', 'خوف : ظلام'], correct: 1 },
  { id: 12, section: 'lafzy', subsection: 'analogy', q: 'شمس : ضوء', options: ['نار : دخان', 'نار : حرارة', 'ماء : عطش', 'ريح : سحاب'], correct: 1 },
  { id: 13, section: 'lafzy', subsection: 'analogy', q: 'مفتاح : قفل', options: ['باب : غرفة', 'حذاء : قدم', 'كلمة سر : حساب', 'ساعة : وقت'], correct: 2 },
  { id: 14, section: 'lafzy', subsection: 'analogy', q: 'شجاع : جبان', options: ['كريم : معطاء', 'بخيل : شحيح', 'أبيض : أسود', 'كبير : عظيم'], correct: 2 },
  { id: 15, section: 'lafzy', subsection: 'analogy', q: 'جمل : قافلة', options: ['نجم : مجرة', 'كتاب : مكتبة', 'طائر : سرب', 'ورقة : دفتر'], correct: 2 },
  { id: 16, section: 'lafzy', subsection: 'analogy', q: 'مطر : فيضان', options: ['نار : رماد', 'ريح : إعصار', 'بحر : موج', 'ثلج : برد'], correct: 1 },

  { id: 17, section: 'lafzy', subsection: 'completion', q: 'إنَّ الـ.......... عن الحقِّ صفةٌ ذميمة، تُورثُ صاحبَها هلاكَ الدنيا والآخرة.', options: ['إصرار', 'إعراض', 'إقبال', 'اقتراب'], correct: 1 },
  { id: 18, section: 'lafzy', subsection: 'completion', q: 'لا يُمكن أن يبلغ المرءُ غايتَه إلا بـ.......... و.......... .', options: ['الكسل والإهمال', 'العزيمة والصبر', 'التردد والخوف', 'الاستعجال والقلق'], correct: 1 },
  { id: 19, section: 'lafzy', subsection: 'completion', q: 'كثيرٌ من الناس يبدؤون أعمالهم بحماسٍ شديد، ثم ما يلبثون أن يَـ.......... .', options: ['يستمرّوا', 'يُكمِلوا', 'يَفتُروا', 'يَتجدَّدوا'], correct: 2 },
  { id: 20, section: 'lafzy', subsection: 'completion', q: 'العاقلُ من اتّعظ بـ.......... غيره، فلا يقعُ فيما وقعوا فيه.', options: ['نجاح', 'ثروة', 'أخطاء', 'أسفار'], correct: 2 },
  { id: 21, section: 'lafzy', subsection: 'completion', q: 'إنَّ القراءةَ نافذةٌ تُطلّ بنا على .......... .', options: ['الجهل', 'عالمٍ أرحب وأوسع', 'العزلة', 'الضيق'], correct: 1 },
  { id: 22, section: 'lafzy', subsection: 'completion', q: 'لم يكن .......... وحدَه كافيًا للنجاح، بل لا بدَّ من العمل المتواصل.', options: ['الحلم', 'اليأس', 'الكسل', 'الإهمال'], correct: 0 },
  { id: 23, section: 'lafzy', subsection: 'completion', q: 'تُعدُّ الأسرةُ .......... الأولى للطفل، فيها يتلقّى أولى دروس الحياة.', options: ['العائق', 'العدو', 'المدرسة', 'المعارضة'], correct: 2 },
  { id: 24, section: 'lafzy', subsection: 'completion', q: 'كلَّما زاد عِلمُ الإنسان زاد .......... وتواضعُه أمام الحقيقة.', options: ['غروره', 'تكبّره', 'إدراكُه لجهله', 'استهتاره'], correct: 2 },

  { id: 25, section: 'lafzy', subsection: 'error', q: 'كان المعلمُ مُخلصًا في عمله، صبورًا على طلابه، حقودًا في توجيهاتِه، حريصًا على تفوّقهم. الكلمة الشاذة:', options: ['مُخلصًا', 'صبورًا', 'حقودًا', 'حريصًا'], correct: 2 },
  { id: 26, section: 'lafzy', subsection: 'error', q: 'نهضت الأمم بالعلم والعمل والتخطيط والكسل، فلا سبيل لها دون ذلك. الكلمة الشاذة:', options: ['العلم', 'العمل', 'التخطيط', 'الكسل'], correct: 3 },
  { id: 27, section: 'lafzy', subsection: 'error', q: 'يتميّز الجاهلُ بسرعة الحُكم، وقلّة التَّأنّي، وغزارة العلم، وضعف التفكير. الكلمة الشاذة:', options: ['سرعة الحكم', 'قلة التأني', 'غزارة العلم', 'ضعف التفكير'], correct: 2 },
  { id: 28, section: 'lafzy', subsection: 'error', q: 'تتطلّب الكتابةُ الجيدةُ ثروةً لغوية، وفكرًا منظَّمًا، وعشوائيةً في الطرح، وسلامةً في الأسلوب. الكلمة الشاذة:', options: ['ثروةً لغوية', 'فكرًا منظَّمًا', 'عشوائيةً في الطرح', 'سلامةً في الأسلوب'], correct: 2 },
  { id: 29, section: 'lafzy', subsection: 'error', q: 'يحرص الناجحون على إدارة الوقت، ووضع الأهداف، وتجاهل التخطيط، ومتابعة الأداء. الكلمة الشاذة:', options: ['إدارة الوقت', 'وضع الأهداف', 'تجاهل التخطيط', 'متابعة الأداء'], correct: 2 },
  { id: 30, section: 'lafzy', subsection: 'error', q: 'يجبُ على المسافر أن يحضر جوازَه، وتأشيرتَه، وأمتعتَه، وأعداءَه قبل السفر. الكلمة الشاذة:', options: ['جوازه', 'تأشيرته', 'أمتعته', 'أعداءه'], correct: 3 },
  { id: 31, section: 'lafzy', subsection: 'error', q: 'تتميّز البيئة الصحراوية بارتفاع الحرارة، وشُحّ الأمطار، وكثرة الأنهار، وقلة النباتات. الكلمة الشاذة:', options: ['ارتفاع الحرارة', 'شح الأمطار', 'كثرة الأنهار', 'قلة النباتات'], correct: 2 },
  { id: 32, section: 'lafzy', subsection: 'error', q: 'من صفات القائد الحكيم: حسنُ الاستماع، وعدلُ الحكم، وتسرّعُ القرار، ورحابةُ الصدر. الكلمة الشاذة:', options: ['حسن الاستماع', 'عدل الحكم', 'تسرع القرار', 'رحابة الصدر'], correct: 2 },

  { id: 33, section: 'lafzy', subsection: 'reading', passage: 'تُعدُّ القراءة من أعظم وسائل تنمية العقل، فهي ليست مجرّد فكّ رموز اللغة، بل عمليةٌ ذهنيةٌ معقّدة تشمل الفهم والتحليل والاستنتاج. وقد أثبتت الدراسات أنَّ الذين يقرؤون باستمرار يتمتّعون بقدرات تفكير أعلى من غيرهم، وذاكرة أقوى، وحصيلة لغوية أوسع. ومع ذلك، فإنَّ القراءة في العصر الحديث تواجه تحدياتٍ كبيرةً، أبرزُها انتشار وسائل التواصل الاجتماعي. ولكي نحافظ على عادة القراءة ينبغي تخصيص وقتٍ يومي لها، واختيار كتبٍ ذاتِ قيمة، ومناقشة ما نقرؤه مع الآخرين.', q: 'الفكرة الرئيسية في النص هي:', options: ['انتقاد وسائل التواصل', 'أهمية القراءة وكيفية الحفاظ عليها', 'تاريخ القراءة', 'أنواع الكتب'], correct: 1 },
  { id: 34, section: 'lafzy', subsection: 'reading', q: 'وفقًا للنص، فإن الذين يقرؤون باستمرار يتمتعون بـ:', options: ['ثروة مالية أكبر', 'صحة جسدية أفضل', 'قدرات تفكير وذاكرة وحصيلة لغوية أعلى', 'مكانة اجتماعية'], correct: 2 },
  { id: 35, section: 'lafzy', subsection: 'reading', q: 'ما أبرز التحديات التي تواجه القراءة في العصر الحديث؟', options: ['غلاء أسعار الكتب', 'انتشار وسائل التواصل الاجتماعي', 'قلة المكتبات', 'صعوبة اللغة'], correct: 1 },
  { id: 36, section: 'lafzy', subsection: 'reading', q: 'أيُّ ممّا يلي ليس من توصيات الكاتب للحفاظ على عادة القراءة؟', options: ['تخصيص وقت يومي', 'اختيار كتب ذات قيمة', 'مناقشة ما نقرؤه', 'قراءة الكتب القصيرة فقط'], correct: 3 },

  { id: 37, section: 'lafzy', subsection: 'reading', passage: 'يُعدُّ الماءُ سرَّ الحياة على كوكب الأرض. ومع أنَّ ثلاثة أرباع سطح الأرض مغطّاةٌ بالماء، إلا أنَّ نسبةَ المياه العذبة الصالحة للشرب لا تتجاوز 3% من إجمالي المياه. ويواجه العالمُ اليوم أزمةً متناميةً في المياه بسبب التغيّر المناخي، والاستهلاك المتزايد، وتلوّث المصادر المائية. ويُحذِّر العلماء من أنَّ ثلثَ سكان العالم سيعانون من شُحّ المياه بحلول عام 2030.', q: 'النسبة المئوية للمياه العذبة الصالحة للشرب:', options: ['3%', '30%', '75%', '97%'], correct: 0 },
  { id: 38, section: 'lafzy', subsection: 'reading', q: 'من أسباب أزمة المياه العالمية المذكورة في النص:', options: ['انخفاض درجات الحرارة', 'كثرة الأنهار', 'التغيّر المناخي والتلوّث', 'ازدياد الغطاء النباتي'], correct: 2 },
  { id: 39, section: 'lafzy', subsection: 'reading', q: 'ثلث سكان العالم سيعانون من شُحّ المياه بحلول عام:', options: ['2025', '2030', '2050', '2100'], correct: 1 },
  { id: 40, section: 'lafzy', subsection: 'reading', q: 'أيُّ ممّا يلي من الحلول لمواجهة أزمة المياه؟', options: ['زيادة استهلاك المياه', 'ترشيد الاستهلاك وتحلية المياه', 'إغلاق محطات التحلية', 'منع جمع الأمطار'], correct: 1 },
];

export const QUANT_QUESTIONS = [
  { id: 41, section: 'kammi', subsection: 'arithmetic', q: 'ما ناتج: 25% من 240؟', options: ['40', '50', '60', '80'], correct: 2 },
  { id: 42, section: 'kammi', subsection: 'arithmetic', q: 'إذا كان س + 3 = 11، فإن قيمة 2س − 5 تساوي:', options: ['11', '13', '15', '17'], correct: 0 },
  { id: 43, section: 'kammi', subsection: 'arithmetic', q: 'اشترى تاجر سلعةً بـ 800 ريال، وباعها بـ 1000 ريال. نسبة الربح:', options: ['15%', '20%', '25%', '30%'], correct: 2 },
  { id: 44, section: 'kammi', subsection: 'arithmetic', q: 'مجموع ثلاثة أعداد متتابعة يساوي 78. أصغرها هو:', options: ['24', '25', '26', '27'], correct: 1 },
  { id: 45, section: 'kammi', subsection: 'arithmetic', q: 'إذا كان متوسط 5 أعداد هو 12، فإن مجموعها يساوي:', options: ['48', '55', '60', '72'], correct: 2 },
  { id: 46, section: 'kammi', subsection: 'arithmetic', q: 'ما الرقم التالي في النمط: 2، 6، 12، 20، 30، ...؟', options: ['38', '40', '42', '44'], correct: 2 },
  { id: 47, section: 'kammi', subsection: 'arithmetic', q: 'ربعُ عددٍ يساوي ثلثَ العدد 24. هذا العدد هو:', options: ['24', '28', '32', '36'], correct: 2 },
  { id: 48, section: 'kammi', subsection: 'arithmetic', q: 'إذا قطعت سيارة 240 كم في 4 ساعات، فإن سرعتها المتوسطة:', options: ['50 كم/س', '60 كم/س', '70 كم/س', '80 كم/س'], correct: 1 },
  { id: 49, section: 'kammi', subsection: 'arithmetic', q: 'ما ناتج: (3 × 4) + (8 ÷ 2) − 5؟', options: ['9', '11', '13', '15'], correct: 1 },
  { id: 50, section: 'kammi', subsection: 'arithmetic', q: 'إذا كان نصف عدد + 7 = 15، فإن العدد:', options: ['8', '14', '16', '22'], correct: 2 },
  { id: 51, section: 'kammi', subsection: 'arithmetic', q: 'خُصِم 20% من سعر سلعة فأصبح سعرها 320 ريالاً. سعرها الأصلي:', options: ['360 ريال', '380 ريال', '400 ريال', '420 ريال'], correct: 2 },
  { id: 52, section: 'kammi', subsection: 'arithmetic', q: 'عدد الأعداد الفردية بين 10 و 30:', options: ['9', '10', '11', '12'], correct: 1 },
  { id: 53, section: 'kammi', subsection: 'arithmetic', q: 'إذا كان أ + ب = 12 و أ − ب = 4، فإن قيمة أ:', options: ['4', '6', '8', '10'], correct: 2 },
  { id: 54, section: 'kammi', subsection: 'arithmetic', q: 'ينجز عامل عملاً في 6 أيام، فكم يومًا يحتاج عاملان لإنجازه؟', options: ['2', '3', '4', '12'], correct: 1 },
  { id: 55, section: 'kammi', subsection: 'arithmetic', q: 'النسبة بين الطلاب والطالبات 3:2. إذا كان عدد الطلاب 18، فعدد الطالبات:', options: ['10', '12', '14', '15'], correct: 1 },
  { id: 56, section: 'kammi', subsection: 'arithmetic', q: 'ما الجذر التربيعي للعدد 144؟', options: ['10', '11', '12', '14'], correct: 2 },

  { id: 57, section: 'kammi', subsection: 'geometry', q: 'محيط مستطيل طوله 12 سم وعرضه 5 سم:', options: ['17 سم', '24 سم', '34 سم', '60 سم'], correct: 2 },
  { id: 58, section: 'kammi', subsection: 'geometry', q: 'مساحة دائرة نصف قطرها 7 سم (π = 22/7):', options: ['22 سم²', '44 سم²', '154 سم²', '308 سم²'], correct: 2 },
  { id: 59, section: 'kammi', subsection: 'geometry', q: 'مجموع زاويتين في مثلث 110°، فالزاوية الثالثة:', options: ['60°', '70°', '80°', '90°'], correct: 1 },
  { id: 60, section: 'kammi', subsection: 'geometry', q: 'مكعّب طول حرفه 5 سم. حجمه:', options: ['15 سم³', '25 سم³', '75 سم³', '125 سم³'], correct: 3 },
  { id: 61, section: 'kammi', subsection: 'geometry', q: 'إذا كان قطر دائرة 14 سم، فنصف قطرها:', options: ['6 سم', '7 سم', '14 سم', '28 سم'], correct: 1 },
  { id: 62, section: 'kammi', subsection: 'geometry', q: 'مثلث قائم فيه ضلعا القائمة 3 سم و 4 سم. طول الوتر:', options: ['5 سم', '6 سم', '7 سم', '9 سم'], correct: 0 },
  { id: 63, section: 'kammi', subsection: 'geometry', q: 'مجموع الزوايا الداخلية لشكل رباعي:', options: ['180°', '270°', '360°', '540°'], correct: 2 },
  { id: 64, section: 'kammi', subsection: 'geometry', q: 'مساحة متوازي أضلاع قاعدته 10 سم وارتفاعه 6 سم:', options: ['30 سم²', '60 سم²', '16 سم²', '32 سم²'], correct: 1 },

  { id: 65, section: 'kammi', subsection: 'data', passage: 'درجات طالب في خمس مواد: عربية 85، رياضيات 92، علوم 78، إنجليزي 88، اجتماعيات 82.', q: 'مجموع درجات الطالب:', options: ['415', '420', '425', '430'], correct: 2 },
  { id: 66, section: 'kammi', subsection: 'data', q: 'متوسط درجات الطالب:', options: ['83', '84', '85', '86'], correct: 2 },
  { id: 67, section: 'kammi', subsection: 'data', q: 'النسبة المئوية لدرجة الرياضيات:', options: ['88%', '90%', '92%', '94%'], correct: 2 },
  { id: 68, section: 'kammi', subsection: 'data', q: 'الفرق بين أعلى وأقل درجة:', options: ['10', '12', '14', '16'], correct: 2 },
  { id: 69, section: 'kammi', subsection: 'data', q: 'عدد المواد التي حصل فيها على درجة أعلى من 85:', options: ['1', '2', '3', '4'], correct: 1 },
  { id: 70, section: 'kammi', subsection: 'data', q: 'لرفع متوسطه إلى 90، يحتاج مجموع إضافي قدره:', options: ['25', '30', '35', '40'], correct: 0 },

  { id: 71, section: 'kammi', subsection: 'comparison', q: 'س = 25% من 80    ,    ص = 20% من 100', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 2 },
  { id: 72, section: 'kammi', subsection: 'comparison', q: 'س = 3² + 4²    ,    ص = 5²', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 2 },
  { id: 73, section: 'kammi', subsection: 'comparison', q: 'س = مساحة مربع طول ضلعه 6    ,    ص = مساحة مستطيل أبعاده 4 و 9', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 0 },
  { id: 74, section: 'kammi', subsection: 'comparison', q: 'س = أصغر عدد أوّلي أكبر من 10    ,    ص = أكبر عدد أوّلي أقل من 14', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 2 },
  { id: 75, section: 'kammi', subsection: 'comparison', q: 'إذا كان أ × ب = 0   ,   س = أ    ,    ص = ب', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 3 },
  { id: 76, section: 'kammi', subsection: 'comparison', q: 'س = (−3)²    ,    ص = −3²', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 0 },
  { id: 77, section: 'kammi', subsection: 'comparison', q: 'س = عدد الدقائق في ساعتين    ,    ص = عدد الثواني في دقيقتين', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 1 },
  { id: 78, section: 'kammi', subsection: 'comparison', q: 'س = ثلث 90    ,    ص = ربع 120', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 2 },
  { id: 79, section: 'kammi', subsection: 'comparison', q: 'إذا كان: 2س + 3 = 11   ,   س = قيمة س    ,    ص = 5', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 1 },
  { id: 80, section: 'kammi', subsection: 'comparison', q: 'س = محيط دائرة نصف قطرها 7    ,    ص = محيط مربع طول ضلعه 11', options: ['س > ص', 'ص > س', 'س = ص', 'المعلومات غير كافية'], correct: 0 },
];

export const QUDURAT_QUESTIONS = [...VERBAL_QUESTIONS, ...QUANT_QUESTIONS];

export const SUBSECTION_NAMES = {
  vocabulary: 'معاني المفردات',
  analogy: 'التناظر اللفظي',
  completion: 'إكمال الجمل',
  error: 'الخطأ السياقي',
  reading: 'استيعاب المقروء',
  arithmetic: 'المسائل الحسابية',
  geometry: 'الهندسة',
  data: 'تحليل البيانات',
  comparison: 'المقارنات الكمية',
};
